#pragma once

namespace Features
{
    enum class Language : unsigned;
}

namespace Loc
{
    // 일반 사용자 대면 문구는 이 ID를 통해서만 UI에 전달한다. 진단 카운터의 포맷 문자열은
    // 의도적으로 영어를 유지해 로그/수치와 동일한 용어를 사용한다.
    enum class Str
    {
        WindowTitle,
        BrandName,
        BrandSubtitle,
        TabAimbot,
        TabEsp,
        TabMisc,
        TabDebug,
        AimbotDescription,
        EspDescription,
        MiscDescription,
        DebugDescription,
        AimbotEnabled,
        EspEnabled,
        SilentAim,
        ActivationKey,
        DrawFovCircle,
        TargetEnemies,
        TargetPolice,
        OnlyVisibleTargets,
        RequireHealthPool,
        LimitHealthPool,
        MaxHealthPool,
        FovRadius,
        Smoothing,
        AimDistance,
        BoundingBoxes,
        Skeleton,
        HealthBars,
        NativeHighlight,
        HideDeadNpcs,
        VisibilityCheck,
        HideOccludedNpcs,
        Civilians,
        Enemies,
        Police,
        Unclassified,
        MaxDistance,
        NoRecoil,
        NoSpread,
        AutoPistol,
        InfiniteHealth,
        InfiniteStamina,
        ShowFps,
        ShowGraph,
        ShowInternalStats,
        DiagnosticLogging,
        CrashReporting,
        PerformanceProfiling,
        DebuggerOutput,
        HeadlessAimbot,
        Language,
        Korean,
        English,
        Theme,
        Dark,
        Light,
        FooterHotkeys,
        TrainerReady,
        StartupOpenPrefix,
        StartupOpenSuffix,
        InsertKey,
        PressKey,
        ReleaseKeys,
        ActivationSilentHint,
        ActivationClassicHint,
        VisibleOnlyHint,
        HealthFilterHint,
        VisibilityPerformanceHint,
        DiagnosticLoggingHint,
        PerformanceProfilingHint,
        DebuggerOutputHint,
        CrashReportingHint,
        HeadlessAimbotHint,
        MetersFormat,
        DegreesFormat,
        HealthFormat,
        DecimalFormat,
        KeyMouseLeft,
        KeyMouseRight,
        KeyMouseMiddle,
        KeyMouseFour,
        KeyMouseFive,
        KeyBackspace,
        KeyTab,
        KeyEnter,
        KeyShift,
        KeyRightShift,
        KeyControl,
        KeyRightControl,
        KeyAlt,
        KeyRightAlt,
        KeyCapsLock,
        KeySpace,
        KeyPageUp,
        KeyPageDown,
        KeyHome,
        KeyLeft,
        KeyUp,
        KeyRight,
        KeyDown,
        KeyDelete,
        KeyNumpadFormat,
        KeyFunctionFormat,
        KeyHexFormat,
        SilentAimDiagnostics,
        InternalStatsTitle,
        LanguagePopup,
        ThemePopup,
    };

    const char* Text(Str id);
    const char* Text(Str id, Features::Language language);
}
